### PR TITLE
Add support for pushing 8-bit immediates

### PR DESCRIPTION
**Pull request by truls**

### CODE REVIEW

**Comment by weidendo** [comment]
Adding a test would be nice.

Should be similar to tests/cases/integration/fp.s. Such "integration" tests check
decoding, emulation, and generation.

I just see that these tests (currently) do not really check for correct emulation results.
I think the issue there was that tests checking register values currently do
not work with changing addresses on every run.
Still better than nothing...

**Comment by truls** [comment]
Replaced by #31

**Comment by weidendo** [comment]
Good catch.

There Intel manual is bad written.

There is "push 0x5b" and "pushw 0x5b" with operand sizes 64bit and 16bit, respectively, in 64bit mode.
Can you add 16-bit variants somehow to the test? Is the decoder missing here something?
There is a Instr.vt field, which should be used to specify operand width...

**Comment by truls** [comment]
Yes, 16-bit immedaites are unsupported by the decoder. There's a comment saying  // 0x68: push imm32 (imm16 possible, but not generated by "as" - no test) . I'm not quite sure how to add 16-bit imm support though

**Pull request closed without merging**
