### PR TITLE
Improve Travis configuration

### PR DESCRIPTION
**Pull request by aengelke**
- Use container infrastructure
- Prepare for LL back-end builds (meaning LLVM and C++ dependencies)
- Fix buggy test case
- Don't use LLVM 3.6 and 3.8; the first won't compile and the latter produces different IR...

### CODE REVIEW

**Comment by weidendo** [comment]
I tried to extract the fix for the buggy test case "decode/js.s".
But on my laptop, I do get "f1:  78 fe                 js      $f1", not your expected output. Any ideas?

**Comment by weidendo** [comment]
I do not really understand the travis config.
Anyway. We want tests to run with all kind of compilers, including different clang versions.
The LLVM PR should not restrict this, but may use a special LLVM version to link this, and
the tests should still compile with different globally installed compilers. Does this work with
this PR?

**Comment by weidendo** [comment]
Actually, I think that installing the correct LLVM version for the LLVM PR into some subdirectory ("deps") should be done by the Makefile, e.g. using "make deps". Julia Lang does the same.

**Comment by aengelke** [comment]
The only thing `make deps` can do (without fixing on the distribution) is to download the LLVM sources and compile from source. This is also what [Julia](https://github.com/JuliaLang/julia/blob/master/deps/llvm.mk) does. However, this seems to be an overkill for this library. For simplicity, can we assume that the user is able to install/download LLVM himself and to set the `LLVM_CONFIG` (=path to llvm config binary) variable appropriately?

For the JS test case, the only rational thing to do is to drop it or to drop it. Different compilers on different machines produce different code, and in case of assembly this also happens for jumps. I already applied some hacks for Clang in #16 and ended up with removing the disassembly there for exactly this reason.

In general, the content of this PR is now part of #16.

**Pull request closed without merging**
