### PR TITLE
Support RIP-relative addressing

### PR DESCRIPTION
**Pull request by truls**

### CODE REVIEW

**Comment by truls** [comment]
I think it's actually working, but different offsets are generated by different compilers. Even my gcc and the travis gcc seems to generate different binaries. Any ideas on how to make the test cases handle this?

**Comment by weidendo** [comment]
For this, the python test script passes the test output through $(testcase).expect_filter if that file exists. It thus can be very specific for a given test to "normalize" the output to not differ between compilers, see

    ./cases/integration/op-call.s.expect_filter
 
I hope this works here.

**Comment by truls** [comment]
I added an expect filter so the tests passes now but the filter is really invasive. It would be nice to be able to verify a test by, for example, checking the post-test register values against known-good values.

**Comment by weidendo** [comment]
Ah, you mean multiple possible outcomes? Would this work here? I can imagine that sometimes
the number of possible outcomes explodes?

**Comment by weidendo** [comment]
Stalled, waiting for feature to make test case easier to write (registering labeled read-only memory regions).

**Comment by weidendo** [comment]
I just committed @1334acd, which should allow to close this PR. With the help of @4e045b the test does not need any filter.

**Pull request closed without merging**
