### PR TITLE
Major refactoring of test script

### PR DESCRIPTION
**Pull request by aengelke**
The properties in the test case and the driver are now parsed properly and multiple properties can be used at the same time. The script itself is now object-oriented and has a proper argument parser.

If the success of a test is only defined by the return code, there is no need to store an empty *.expect file for it. Consequently, a test case is now defined via the *.c and the *.s files and not via the *.expect files. If a test case has no *.expect file, it is ignored.

If the test case or the driver has the property `nooutput=1`, no output verification or storing will be performed. A test can set the `ccflags` variable which can be included in the compilation command by the test driver.

Finally, this adds tests for the generator and the decoder, which need different drivers.

### CODE REVIEW

**Comment by weidendo** [comment]
Looks good.

However, also for the generator tests, I would prefer the same way as with other tests, using
an *.expect file, i.e. printing a decoded version (including hex bytes) of the generated code.

**Comment by aengelke** [comment]
The idea was to put the instruction and the assembly in one file so that it can be used in both directions: decoding and generating. With *.expect files, we would need to have the instruction and the assembly twice.

Using *.expect files also doesn't make much sense here since the behavior should never update, i.e. the mapping between instruction and binary should always be the same. The reason behind the expect files is that minor updates can happen often (therefore the `--store` option) and generating them by hand is also hard.

**Comment by weidendo** [comment]
Hmm. "mov eax, $00000000" (32bit imm) decoded and generated back to machine code may result in "mov eax, $00" (8bit imm to be extended) or "xor eax, eax", ie. be totally different. So directions often cannot easily be reversed, and we want to test different things: "can I decode everything?" vs. "does it generate the smallest machine code with identical result?". Thus, I do not believe having one test covering the 2 directions is very useful, as it seems to me that reversable cases are exceptions. Then, we just can have separate tests, too.

I do not want any "*.expect" files to change often, because with every change, you *must* check if the change is correct. And this easily becomes a huge pain e.g. with >100 test results changing because of one small code modification. Instead of having "--store" at all (which makes it much too easy to introduce bugs into tests), better make it obvious that tests are crap if expected results change all the time :-)

**Comment by aengelke** [comment]
Changed. However, the question "does it generate the smallest/most efficient/... code" sounds like an (instr/bb/cfg) optimizer pass for me, which could (should?) be separated from the generator.

**Comment by aengelke** [comment]
@weidendo Is this PR obsolete now?

**Comment by weidendo** [comment]
Merged, with slight changes.

**Pull request closed without merging**
