### PR TITLE
Improved and extended emulation of push/pop instructions

### PR DESCRIPTION
**Pull request by truls**
On the x86_64 architecture in 64-bit mode only 64- or 16-bit values can
interact with the stack (SDM vol. 2B, 4.3) since instructions commanding
otherwise are not encodable. Therefore, the previous support for
pushing/popping 32-bit registers (i.e. moving rsp by 4 bytes) was
removed. So now only 16-bit or 64-bit registers can be pushed from or
popped into. Furthermore, support for pushing and popping 8-bit and
16-bit immediate values has been added. All immediate values are
sign-extended to 64-bit. I'm not completely sure if this is the right
thing to do, but it appears to work in practice and gcc seems to make
the assumption that pushing any immediate value decrements rsp by 8.

### CODE REVIEW

**Comment by truls** [comment]
I've updated the patch with support for decoding pushw imm16 instructions and the relevant test case

**Comment by weidendo** [comment]
The decoder addition is almost fine. As far as I see, we have two widths: the width of
the immediate operand (8/16/32), and the instruction operand width (8/64). The first
should be passed to parseImm() as 2nd parameter and is used for c->o1, the latter should
go into c->vt.

This should also fix the assembler printer. Currently, it wrongly shows pushb/pushl for the
first instructions in the test. Hmm... it probably will show "pushq" then (which even may be fine?).

You have the .byte stuff in the test. Doesn't "pushw" work?

**Comment by truls** [comment]
So you want to move the immediate value sign extension to the decoder and then pass OT_Imm64 or OT_Imm16 values to the emulator? Wouldn't that mean that the instruction captured is different from the original? Is that a problem?

Ok. I'll look into the printer.

The clang assembler doesn't like pushw. It works with as.

**Comment by weidendo** [comment]
No, the decoder should not change anything, just use OT_Imm8/16/32 as given in the machine code;
parseImm() should do that when you give it VT_8/16/32. But an Instr struct can store multiple different widths, one in each operand, and one global for the instruction (vt).

BTW, the idea with the printer was to have output identically to default objdump (AT&T syntax).

**Comment by truls** [comment]
The instruction width is now set to 16-bit for pushw and 64-bit for push to all other immediate values. This also seems to make the printer render the assembly the same way as onjfump (pushw for 16-bit immediates and pushq for other sizes.

**Comment by weidendo** [comment]
Merged by hand in a slightly modified way.

**Pull request closed without merging**
